# 考虑到本仓库日常不更新, GitHub Actions 改为 API 触发
on:
  repository_dispatch:
    types:
      - UpstreamRepoSync

name: Sync Upstream Repos For Packaging
jobs:
  run:
    name: Sync Upstream Repos For Packaging
    runs-on: ubuntu-latest
    steps:
    - name: Sync Upstream Repos For Packaging
      uses: DiscuzPack/RepoSync@master
      with:
        private_key: ${{ secrets.PRIVATE_KEY }}
